version: '3'
services: 
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server 
    volumes:
      - /app/node_modules
      - ./server:/app
  mongo:
    ports:
      - '27017:27017'
  nginx:
    ports:
      - '3000:80'